return Def.ActorFrame {
	--Backpart
	LoadActor(THEME:GetPathG("","_Gears/6L_pattern"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y);
	};
	LoadActor(THEME:GetPathG("","_Gears/5U-back_M"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X+96;y,SCREEN_CENTER_Y+59;spin;;effectmagnitude,0,0,-15);
	};
	LoadActor(THEME:GetPathG("","_Gears/5L-back_L"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-65;y,SCREEN_CENTER_Y+162;spin;;effectmagnitude,0,0,7.5);
	};
	LoadActor(THEME:GetPathG("","_Gears/4L-mid_L"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-158;y,SCREEN_CENTER_Y+120;spin;;effectmagnitude,0,0,-7.5);
	};
	LoadActor(THEME:GetPathG("","_Gears/5U-back_M"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X+251;y,SCREEN_CENTER_Y+51;spin;;effectmagnitude,0,0,15);
	};
	LoadActor(THEME:GetPathG("","_Gears/4U-mid_S"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X+280;y,SCREEN_CENTER_Y-4;spin;;effectmagnitude,0,0,-48);
	};
	LoadActor(THEME:GetPathG("","_Gears/4U-mid_M"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X+180;y,SCREEN_CENTER_Y+52;spin;;effectmagnitude,0,0,24);
	};
	LoadActor(THEME:GetPathG("","_Gears/4U-mid_S"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-306;y,SCREEN_CENTER_Y;spin;;effectmagnitude,0,0,30);
	};
	--Frame
	LoadActor(THEME:GetPathG("","_Gears/3L-frame"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y-2);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_L"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X+180;y,SCREEN_CENTER_Y+52;spin;;effectmagnitude,0,0,24);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_L"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-106;y,SCREEN_CENTER_Y+30;spin;;effectmagnitude,0,0,24);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_L"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-294;y,SCREEN_CENTER_Y+42;spin;;effectmagnitude,0,0,24);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_S"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-222;y,SCREEN_CENTER_Y+14;spin;;effectmagnitude,0,0,-96);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_S"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-196;y,SCREEN_CENTER_Y+26;spin;;effectmagnitude,0,0,96);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_S"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-42;y,SCREEN_CENTER_Y-12;spin;;effectmagnitude,0,0,-96);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_M"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X-2;y,SCREEN_CENTER_Y+6;spin;;effectmagnitude,0,0,48);
	};
	LoadActor(THEME:GetPathG("","_Gears/2U-front_M"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X+74;y,SCREEN_CENTER_Y+20;spin;;effectmagnitude,0,0,48);
	};
	Def.ActorFrame {
		ShowPressStartForOptionsCommand=cmd(stoptweening);
		OnCommand=cmd(queuecommand,"Rotation");
		RotationCommand=cmd(linear,0.9375;x,16;y,4;--25%
					  linear,0.9375;x,31;y,13;--50%
					  linear,0.9375;x,40;y,28;--25%
					  linear,0.9375;x,44;y,44;--100%
					  linear,0.9375;x,40;y,60;--25%
					  linear,0.9375;x,31;y,75;--50%
					  linear,0.9375;x,16;y,84;--25%
					  linear,0.9375;x,0;y,88;--100%
					  linear,0.9375;x,-16;y,84;--25%
					  linear,0.9375;x,-31;y,75;--50%
					  linear,0.9375;x,-40;y,60;--25%
					  linear,0.9375;x,-44;y,44;--100%
					  linear,0.9375;x,-40;y,28;--25%
					  linear,0.9375;x,-31;y,13;--50%
					  linear,0.9375;x,-16;y,4;--25%
					  linear,0.9375;x,0;y,0;--100%
		queuecommand,"Rotation");--gear=44pxl from center	  
		LoadActor(THEME:GetPathG("","_Gears/1L-rod_S"))..{
			OnCommand=cmd(x,SCREEN_CENTER_X-200;y,SCREEN_CENTER_Y-6);
		};
		LoadActor(THEME:GetPathG("","_Gears/1L-rod_L"))..{
			OnCommand=cmd(x,SCREEN_CENTER_X+36;y,SCREEN_CENTER_Y-2); 
		};
	};
	--Fade
	LoadActor(THEME:GetPathG("","_Gears/0L-Black_grad"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y+8);
	};
};